version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/stuart # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:9.10.0 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: submodule stuff
          command: git submodule update --init --recursive --remote
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: yarn
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
#      - run: # run tests
#          name: lint
#          command: yarn lint
      - run: # run tests
          name: test
          command: yarn test
      - run:
          name: build
          command: yarn build
      - run:
          name: clone
          command: git clone --depth 1 https://${DOCS_GITHUB_TOKEN}@github.com/rishabh1403/portfolio.git
      - run:
          name: clear old deployment
          command: rm -rf portfolio/*
      - run:
          name: copy deployment
          command: cp -vr build/* portfolio
      - deploy:
          name: Trigger docs deployment
          working_directory: ~/stuart/portfolio
          command: |
            git add .
            git config credential.helper 'cache --timeout=120'
            git config user.email "mailrishabh1403@gmail.com"
            git config user.name "Rishabh Jain"
            git commit --allow-empty -m "Trigger deployment"
            git push -q https://${DEPLOY_KEY}@github.com/rishabh1403/portfolio.git master
            # Push quietly to prevent showing the token in log
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples